### ISSUE TITLE
Upgrade ruby / rails to newer version

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/marketplace#2254]
Ruby should be updated to the newest stable version (`3.0.2`)
Rails should be updated to the newest compatible version

- [x] Upgrade ruby to 2.6.7
- [x] Upgrade ruby to 2.7.3
- [x] Upgrade rails to 6.0.4
- [x] Upgrade rails to 6.1.4
- [x] Upgrade ruby to 3.0.2
- [x] Change from unirest to faraday (should fix the two failing tests in 8c8a047, unirest now throws `NoMethodError: undefined method 'escape' for URI:Module`, but it is consumed in url_helper.rb)
    - replace all references to Unirest with Faraday
    - Faraday has field `status` instead of `code` in responses
    - etc...
- [x] Fix pry-doc ruby 3.0.2 problem - remove pry-doc util it support ruby 3.0.2 -> only dev uses this
- [x] Switch to rails 6.1 defaults (set `config.load_defaults` to 6.1, then remove file `new_framework_defaults_6_1.rb`)
